.TH "tvheadend" 1
.SH NAME
tvheadend \ - Advanced TV streaming server/relay
.SH SYNOPSIS
.B tvheadend
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B Tvheadend
is a streaming server/relay supporting a variety of sources and multiple
output formats. It is primarily intended to be used in together with the
.B Showtime
Media player.
.SH OPTIONS
All arguments are optional.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show built-in help information (may be more up to date).
.TP
\fB\-c\fR, \fB\-\-config\fR
Specify an alternate config path; the default is \fI${HOME}/.hts\fR
.TP
\fB\-f
Fork and become a background process (daemon). Default no.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-user\fR \fIusername\fR
Run as user \fIusername\fR. Only applicable if daemonizing. Default is to
use the uid of 1 (daemon on most systems).
.TP
\fB\-g\fR \fIgroupname\fR, \fB\-\-group \fR\fIgroupname\fR
Run as group \fR\fIgroupname\fR. Only applicable if daemonizing. Default is to use the 'video' group. If the 'video' group does not exist, gid 1 (daemon) will be used.
.TP
\fB\-p\fR \fIpidpath\fR, \fB\-\-pid \fR\fIpidpath\fR
Specify alternative PID path file (default /var/run/tvheadend.pid).
.TP
\fB\-C\fR, \fB\-\-firstrun\fR
If no user account exist then create one with no username and no
password. Use with care as it will allow world-wide administrative
access to your Tvheadend installation until you edit the
access-control from within the Tvheadend UI.
.TP
\fB\-a\fR, \fB\-\-adapters\fR
Only use specified DVB adapters (comma separated).
.TP
\fB\-6\fR, \fB\-\-ipv6\fR
Listen on IPv6.
.TP
\fB\-b\fR \fIaddress\fR, \fB\-\-bindaddr\fR \fIaddress\fR
Specify an interface IP address on which incoming HTTP and HTSP connections
will be accepted. By default, connections are accepted on all interfaces.
.TP
\fB\-\-http_port
Specify alternative http port (default 9881).
.TP
\fB\-\-http_root
Specify alternative http webroot.
.TP
\fB\-\-htsp_port
Specify alternative HTSP port (default 9882).
.TP
\fB\-\-htsp_port2
Specify extra HTSP port.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable all debug.
.TP
\fB\-s\fR, \fB\-\-syslog\fR
Enable debug to syslog.
.TP
\fB\-\-uidebug
Enable web UI debug.
.TP
\fB\-l\fR, \fB\-\-log\fR
Log to file.
.TP
\fB\-A\fR, \fB\-\-abort\fR
Immediately abort on startup (for debug).
.TP
\fB\-\-noacl
Do not perform any access control checking.
.TP
\fB\-R\fR, \fB\-\-dvbraw\fR
Use rawts file to create virtual adapter.
.TP
\fB\-r\fR, \fB\-\-rawts\fR
Use rawts file to generate virtual services.
.TP
\fB\-j\fR, \fB\-\-join\fR
Subscribe to a service permanently.
.SH "LOGGING"
All activity inside tvheadend is logged to syslog using log facility
\fBLOG_DAEMON\fR.
.SH "SETUP"
.SS "Access to video adapters"
In order for Tvheadend to control the video adapters on the system it
must be granted access to those devices. Most systems have a 'video'
group with write access to the video adapter devices. When Tvheadend
is started as a daemon it will automatically change its primary group
to 'video' in order to access these groups. If your system is configured
in a different way you can either change the group membership of the
video adapters (/dev/dvb, etc) or reconfigure the Tvheadend startup
parameters. This is most likely the behavior if you have installed
Tvheadend from a distribution package.
.PP
If Tvheadend is started without the '-f' argument it will not daemonize
nor change its primary userid/groupid. Rather it will run with the permissions
granted to the user executing the binary. If that's the case you must make
sure the current user is granted with access to the video devices.
.SS "Configuration"
All configuration in Tvheadend is maintained via its embedded web server running on port 9981. Just point your browser to:
.PP
.nf
   http://hostname:9981/
.fi
.PP
By default \fIeveryone (also from remote hosts)\fR is allowed \fIfull\fR
access to \fIall\fR features / settings in the web user interface. If
this is the first time you setup Tvheadend you are most encouraged to
enter the web user interface, selected the 'Configuration' + 'Access Control'
tab and make reasonable changes. Further help / documentation can be obtained
inside the web interface.
.SS "Settings"
Settings are stored in the current users home directory. Thus, if Tvheadend
is run as a system daemon a dedicated user needs to be created and Tvheadend
should be launched with the '-u' argument. Also notice that XMLTV will read
store cache and configuration from the user home directory.
.PP
If daemonizing, tvheadend will writes it pid in /var/run/tvheadend.pid
.SH "AUTHOR"
.B Tvheadend
and this man page is maintained by Andreas Oeman
.PP
(andreas a tvheadend d org)
.PP
You may also visit #hts at irc.freenode.net
.SH "SEE ALSO"
.BR https://tvheadend.org
