#!/bin/sh -e

HTS_USER=hts

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
purge)
    if getent passwd $HTS_USER >/dev/null; then
        HTS_HOME=`getent passwd $HTS_USER | cut -d':' -f6`
        rm -rf "${HTS_HOME}/.hts/tvheadend"
    fi
    if db_get tvheadend/admin_username; then
       db_reset tvheadend/admin_username;
    fi

    if db_get tvheadend/admin_password; then
       db_reset tvheadend/admin_password;
    fi
   ;;
esac

exit 0
