name: Add comment
on:
  pull_request_target:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'SQUASH'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          BODY: >
            Please squash your commits together in order to get htem merged
            :sparkles: Thank you for your contribution! :sparkles:
